services:
  database:
    image: postgres:17
    env_file: 
      - database/.env.local
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend: 
    build: ./backend
    ports:
      - "8000:8080"
    env_file:
      - backend/.env.local
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local
    depends_on:
      - backend
volumes:
  dbdata: