spring.application.name=backend
spring.config.import=optional:file:../../.env.local
spring.datasource.url=jdbc:postgresql://database:5432/recipe_maker_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect